#!/bin/bash

#----------------------#
# Git Credential Setup #
#----------------------#

git_setup

# move out of the project directory
cd ..|| exit 1

# get the current directory
CURRENT_DIR="${PWD}"

# clone CI_DOCS_PROJECT_PATH: group/project-name
if [ -n "$BITBUCKET_BRANCH" ]; then
  git clone git@bitbucket.org:"$BITBUCKET_REPO_OWNER"/"$CI_DOCS_PROJECT_PATH".git
  CI_PROJECT="$BITBUCKET_REPO_SLUG"
elif [ -n "$CI_COMMIT_REF_NAME" ]; then
  git clone git@gitlab.com:"$CI_DOCS_PROJECT_PATH".git
  CI_PROJECT="$CI_PROJECT_NAME"
fi

# move into the docs project directory
cd "$CI_DOCS_PROJECT_NAME" || exit 1

# remove the previous project, if it exists. if it doesn't exist, create it
rm -rf "$CI_PROJECT"
mkdir "$CI_PROJECT"

# move into the directory
cd "$CI_PROJECT" || exit 1

# copy all files from $CI_PROJECT docs to here
cp "${CURRENT_DIR}"/"${CI_PROJECT}"/docs/* .

# return to docs dir for git commit
cd "${CURRENT_DIR}"/"${CI_DOCS_PROJECT_NAME}" || exit 1

# git add and git commit these changes with [skip-ci]
git add .
git commit -m ":heavy_plus_sign: update docs for ${CI_PROJECT} [skip ci]"
git push origin master
