#!/bin/sh

echo "Checking out $BRANCH_NAME..."
git fetch
git checkout "$BRANCH_NAME"
git branch --list
# Forcefully ensure that the local branch is exactly the same as the remote.
git reset --hard origin/"$BRANCH_NAME"
echo "$BRANCH_NAME checked out."
