#!/bin/bash

# check node version:
echo "node version: $(node --version)"

# check package manager version:
if [ -f yarn.lock ]; then
  echo "yarn version: $(yarn --version)"
else
  echo "npm version: $(npm --version)"
fi

# Add npm credentials to container's .npmrc
if [ -n "$ARGO_NPMRC" ]; then
  echo "Setting up npm credentials..."
  echo -e "$ARGO_NPMRC" > ~/.npmrc
  echo "npm credentials configured."
fi

if [ -f package.json ]; then
  echo "Installing dependencies..."
  if [ -f yarn.lock ]; then
    if ! yarn install --pure-lockfile --silent; then
      exit 1
    fi
  else
    if ! npm ci -q --unsafe-perm; then
      exit 1
    fi
  fi
  echo "Dependencies installed."
else
  echo "No package.json in project. Moving on."
fi
